# Generated by Django 5.0.4 on 2024-04-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_jobtype_career_requirements_career_responsibilities_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website", models.URLField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name="career",
            name="job_type",
            field=models.ManyToManyField(related_name="job_type", to="home.jobtype"),
        ),
    ]
