# Generated by Django 5.0.4 on 2024-04-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_enquiry_alter_career_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="message",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
