# Generated by Django 5.0.4 on 2024-04-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_contactus_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
