# Generated by Django 5.0.4 on 2024-05-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_contactus_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="carousel",
            name="count",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="carousel",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="carousel/videos/"),
        ),
        migrations.AlterField(
            model_name="carousel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="carousel/images"),
        ),
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=models.ImageField(upload_to="clients/logo/"),
        ),
    ]
