# Generated by Django 5.0.4 on 2024-05-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_carousel_count_carousel_video_alter_carousel_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carousel",
            old_name="count",
            new_name="item_count",
        ),
        migrations.AlterField(
            model_name="carousel",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="carousel/images/"
            ),
        ),
    ]
