# Generated by Django 5.0.4 on 2024-05-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_rename_count_carousel_item_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplyJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("cover_letter", models.TextField()),
                ("resume", models.FileField(upload_to="resume/")),
            ],
        ),
    ]
