# Generated by Django 5.0.4 on 2024-05-11 12:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_applyjob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="description",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="image",
        ),
        migrations.AddField(
            model_name="blog",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(default=""),
        ),
    ]
