# Generated by Django 5.0.4 on 2024-05-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_blog_sample_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carousel",
            name="item_count",
        ),
        migrations.RemoveField(
            model_name="carousel",
            name="video",
        ),
        migrations.AlterField(
            model_name="service",
            name="logo",
            field=models.CharField(max_length=100),
        ),
    ]
