# Generated by Django 5.0.4 on 2024-05-17 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_blog_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="carousel",
            name="service",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="home.service",
            ),
        ),
    ]
